---
name: action_cable_notes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127964
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/412823
milestone: '16.3'
type: development
group: group::project management
default_enabled: false
