---
name: ai_related_settings
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/118222
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/408791
milestone: '16.0'
type: development
group: group::ai-enablement
default_enabled: false
