---
name: anthropic_experimentation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119729
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/409939
milestone: '16.0'
type: development
group: group::ai-enablement
default_enabled: false
