---
name: batched_api_mergeability_checks
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121980
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/413232
milestone: '16.1'
type: development
group: group::code review
default_enabled: true
