---
name: bitbucket_server_parallel_importer
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/120931
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/411796
milestone: '16.1'
type: development
group: group::import and integrate
default_enabled: true
