---
name: chat_epic_identifier
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128487
rollout_issue_url:
milestone: '16.3'
type: development
group: group::ai framework
default_enabled: false
