---
name: ci_partitioning_use_ci_builds_routing_table
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122919
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421180
milestone: '16.3'
type: development
group: group::pipeline execution
default_enabled: false
