---
name: command_palette
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121932
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/413060
milestone: '16.1'
type: development
group: group::foundations
default_enabled: true
