---
name: enable_hamilton_in_usage_quotas_ui
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/123480
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/411855
milestone: '16.1'
type: development
group: group::purchase
default_enabled: false
