---
name: explain_vulnerability_vertex
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/118754
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/409182
milestone: '16.0'
type: development
group: group::threat insights
default_enabled: false
