---
name: mobile_devops_projects_promo
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/120144
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/410601
milestone: '16.0'
type: development
group: group::mobile devops
default_enabled: false
