---
name: mr_activity_filters
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/115383
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/412432
milestone: '15.11'
type: development
group: group::code review
default_enabled: true
