---
name: nuget_normalized_version
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121260
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/420290
milestone: '16.3'
type: development
group: group::package registry
default_enabled: false
