---
name: self_managed_code_suggestions_completion_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/125563
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/418795
milestone: '16.3'
type: development
group: group::application performance
default_enabled: true
