---
name: summarize_review_vertex
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127190
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/419374
milestone: '16.3'
type: development
group: group::code review
default_enabled: false
