---
name: use_primary_store_as_default_for_etag_cache
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127705
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/419889
milestone: '16.3'
type: development
group: group::scalability
default_enabled: false
