---
data_category: optional
key_path: counts.in_product_marketing_email_verify_2_cta_clicked
description: Total clicks on the verify track's third email
product_section: 'TBD'
product_stage: growth
product_group: activation
value_type: number
status: active
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56752
time_frame: all
data_source: database
instrumentation_class: InProductMarketingEmailCtaClickedMetric
options:
  track: verify
  series: 2
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
