inherit_from:
  - ../config/rubocop.yml

# FIXME once Gitlab::Json is in a gem
Gitlab/Json:
  Enabled: false

# FIXME
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
